# Application name
spring.application.name=${SPRING_APPLICATION_NAME}
# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Google OAuth
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=${GOOGLE_SCOPE}
# Gmail SMTPs
spring.mail.host=${EMAIL_HOST}
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
# Multipart
spring.servlet.multipart.enabled=${MULTIPART_ENABLED}
spring.servlet.multipart.max-file-size=${MULTIPART_MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${MULTIPART_MAX_REQUEST_SIZE}
# eSewa Payment
esewa.product-code=${ESEWA_PRODUCT_CODE}
esewa.secret-key=${ESEWA_SECRET_KEY}
esewa.payment-url=${ESEWA_PAYMENT_URL}
esewa.success-url=${ESEWA_SUCCESS_URL}
esewa.failure-url=${ESEWA_FAILURE_URL}