package com.ecommerce.ecommercewebsite.enums;

public enum AuthErrorCode {
    INVALID_CREDENTIALS,
    NOT_VERIFIED,
    OTP_EXPIRED,
    USER_NOT_FOUND,
    VENDOR_NOT_FOUND,
    USER_ALREADY_EXISTS,
    INVALID_OTP,
    VERIFIED,
    PASSWORD_NOT_MATCH,
    NEW_PASSWORD_AND_OLD_PASSWORD_MATCH,
    NOT_APPROVED,
    BUSINESS_PROFILE_NOT_FOUND,
    PROFILE_NOT_FOUND,
    PROFILE_UPLOAD_FAILURE,
    INVALID_INPUTS,
    INVALID_STATUS,
    PROFILE_ALREADY_EXISTS,


}
