package com.ecommerce.ecommercewebsite.enums;

public enum ProductErrorCode {
    DISTRICT_NOT_FOUND,
    CATEGORY_NOT_FOUND,
    PRODUCT_VARIANTS_NOT_FOUND,
    PRODUCT_ALREADY_EXIST,
    PRODUCT_ALREADY_DELETED,
    PRODUCT_IMAGE_NOT_FOUND,
    CART_ITEM_NOT_FOUND,
    CART_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    UNAUTHORIZED_PRODUCT_ACCESS,
    QUANTITY_NOT_ENOUGH,
    VENDOR_ORDER_NOT_FOUND,
    VENDOR_ORDER_ALREADY_EXIST,
}
