package com.ecommerce.ecommercewebsite.enums;

public enum ProductErrorCode {
    DISTRICT_NOT_FOUND,
    CATEGORY_NOT_FOUND,
    PRODUCT_VARIANTS_NOT_FOUND,
    PRODUCT_ALREADY_EXIST,
    PRODUCT_ALREADY_DELETED,
    PRODUCT_IMAGE_NOT_FOUND,
    CART_ITEM_NOT_FOUND,
    CART_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    UNAUTHORIZED_PRODUCT_ACCESS,
    QUANTITY_NOT_ENOUGH,
    VENDOR_ORDER_NOT_FOUND,
    VENDOR_ORDER_ALREADY_EXIST,
    CATEGORY_ALREADY_EXISTS,
    IMAGE_UPLOADED_FAILED,
    INVALID_PRODUCT_STATUS,
    REQUEST_ALREADY_EXISTS,
    FEATURED_PRODUCT_REQUEST_NOT_FOUND,
    UNAUTHORIZED_STATUS_CHANGE,
    PRODUCT_NOT_EDITABLE,
    PRODUCT_ALREADY_FEATURED

}
